### ISSUE TITLE
i have installed tensorflow and it has method of tf trt 

### ISSUE THREAD

**Issue by navdeep1604** [tensorflow/tensorrt#104]
hello, i am starting tf trt . i just need to know that my tensorflow installation gives method of from tensorflow.contrib import tensorrt as tftrt . As now I have converted my graph into tf rt graph. i was worried that do i need to explicitly install tensor rt packages also . or only conda install tensorflow-gpu and above methods from contrib is what we have to do . as for single file inference , i saw only .06 seconds better performance . please let me know

**Comment by austingg** [comment]
you can only use tf-trt with nvidia-tensorflow container  or build tensorflow with tensorrt enabled from source.

**Comment by pooyadavoodi** [comment]
@navdeep1604 You would need to install TensorRT if you want to use TF-TRT.

It's possible that TensorRT is not being used in your graph and that's why you don't get good performance. 

Closing. 
In case the problem persists, please reopen and post the verbose log of you run.
https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#verbose
