### ISSUE TITLE
No TRTEngineOp

### ISSUE THREAD

**Issue by xusworld** [tensorflow/tensorrt#16]
after trt.create_inference_graph() , still no "TRTEngineOp", why?

**Comment by pooyadavoodi** [comment]
There could be many different reasons. It's hard to say without having more details such as a log, scripts, models, etc.

**Comment by iariav** [comment]
Hi,
i am also facing the same issue, trying to convert the official Deeplab v3+ model from tensorflow/models/research. after converting my frozen_graph to a trt_graph, if i run the code:

`trt_engine_opts = len([1 for n in trt_graph.node if str(n.op) == 'TRTEngineOp'])`

i get that` trt_engine_opts = 0`. this happens in both fp32 and fp16. still trying to understand why this happens.. any help would be greatly appreciated!

p.s
due to the same reason, i also can't convert to INT8 and i get the error massage:

> ERROR:tensorflow:Not a calib graph. Doesn't seem to contain any calibration nodes.

My machine info:
Ubuntu 16.04
Titan RTX
Nvidia Driver Version: 418.56
CUDA Version: 10.0
CUDNN version : 7.5.0
Tensorflow version 1.13.1 from binary
Tensorrt version: (5.1.2.2)

**Comment by xxllp** [comment]
too bad

**Comment by huaifeng1993** [comment]
have you solved this problem?
